title: Ishan Vyas
description: >- 
  I do stuff and then document it here. 
baseurl: "" # For personal sites, leave this blank
url: "https://ishansvyas.github.io" # Your site's URL

# Optional: Information about you or the site
author: 
  name: "Ishan Vyas"
  email: "Ishan [dot] Vyas [at] Duke [dot] edu"

# Markdown and highlighter settings
markdown: kramdown
highlighter: rouge

# Theme (doesn't work)
theme: jekyll-theme-minimal

# Navigation
navigation:
- title: "Home"
  url: "/"
- title: "Projects"
  url: "/projects/"
- title: "Resume"
  url: "/resume/"
- title: "About"
  url: "/about/"

